import os
from datetime import datetime
from src.reporting.charts import generate_charts


def build_report(query: str, crew_output: str, output_dir: str) -> str:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_dir = os.path.join(output_dir, f"report_{timestamp}")
    os.makedirs(report_dir, exist_ok=True)

    # Generate charts
    chart_paths = generate_charts(query, crew_output, report_dir)
    chart_section = "\n".join(
        [f"\n![Chart]({os.path.basename(p)})\n" for p in chart_paths]
    )

    # Assemble final report
    report_md = f"""# Healthcare Research Report
**Query:** {query}
**Generated:** {datetime.now().strftime("%B %d, %Y %H:%M")}
**System:** Healthcare Research Agent v1.0 (4-Agent CrewAI Pipeline)

---

{crew_output}

---

## Visualizations

{chart_section}

---
*Report generated by an autonomous 4-agent AI system: Researcher → Analyzer → Validator → Reporter*
"""

    report_path = os.path.join(report_dir, "executive_report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_md)

    print(f"\n Report saved to: {report_path}")
    print(f" Charts saved to: {report_dir}")
    return report_path
